version: '3.8'

services:
  windward-server:
    build: .
    container_name: windward-horizon-server
    ports:
      - "5137:5137"
    environment:
      - SERVER_NAME=Windward Horizon Dedicated Docker Server
      - SERVER_PORT=5137
      - WORLD_NAME=Default World
      - PUBLIC_SERVER=true
    volumes:
      # Map your Debug, Playuers, and worlds directories
      - /docker/windward-horizon/debug:/home/windwardhorizon/Debug
      - /docker/windward-horizon/players:/home/windwardhorizon/Players
      - /docker/windward-horizon/worlds:/home/windwardhorizon/worlds
    restart: unless-stopped
    # Uncomment the following lines if you want to see logs
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3" 